version: '3.6'

# Template Version 0.1

services:

  wordpress:
    depends_on:
      - mysql
      - phpmyadmin
    image: wordpress:${WORDPRESS_VERSION}
    container_name: ${COMPOSE_PROJECT_NAME}
    ports:
      - ${WORDPRESS_PORT}:80
    restart: always
    environment:
      WORDPRESS_DB_HOST: ${COMPOSE_PROJECT_NAME}_mysql:3306
      WORDPRESS_DB_USER: ${DATABASE_USER}
      WORDPRESS_DB_PASSWORD: ${DATABASE_PASSWORD}
      WORDPRESS_DB_NAME: ${COMPOSE_PROJECT_NAME}_db
    working_dir: /var/www/html
    volumes:
      - "./html:/var/www/html"
      - "./config/php.conf.ini:/usr/local/etc/php/conf.d/php.ini"
    networks:
      - web
      - default

  mysql:
    image: mariadb:${MARIADB_VERSION}
    container_name: ${COMPOSE_PROJECT_NAME}_mysql
    volumes:
      - './mysql:/var/lib/mysql'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${COMPOSE_PROJECT_NAME}_db
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}

  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin:${PHPMYADMIN_VERSION}
    container_name: ${COMPOSE_PROJECT_NAME}_phpmyadmin
    restart: always
    ports:
      - ${PHPMYADMIN_PORT}:80
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

  wpcli:
    build: ./wpcli/
    image: wpcli:latest
    container_name: ${COMPOSE_PROJECT_NAME}_wpcli
    volumes:
      - ./html:/var/www/html
    working_dir: /var/www/html

  healthcheck:
    image: wpcli
    build: ./wpcli/
    container_name: ${COMPOSE_PROJECT_NAME}_healthcheck
    command: sh -c "/wait"
    environment:
      - WAIT_HOSTS=mysql:3306, wordpress:80
      - WAIT_BEFORE_HOSTS=${WAIT_BEFORE_HOSTS:-30}
      - WAIT_AFTER_HOSTS=${WAIT_AFTER_HOSTS:-15}
      - WAIT_HOSTS_TIMEOUT=${WAIT_HOSTS_TIMEOUT:-300}
      - WAIT_SLEEP_INTERVAL=${WAIT_SLEEP_INTERVAL:-30}
      - WAIT_HOST_CONNECT_TIMEOUT=${WAIT_HOST_CONNECT_TIMEOUT:-30}

networks:
  default:
  web:
    external:
      name: web
